redirect file download to Glassfish over 8181 (https) #2013
We're trying this because if we download via Apache going through AJP we
are seeing this for large files (>2 GB):

[2015-04-16T10:31:52.532-0400] [glassfish 4.1] [WARNING] []
[org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid:
_ThreadID=251 _ThreadName=jk-connector(3)] [timeMillis: 1429194712532]
[levelValue: 900] [[ GRIZZLY0013: Exception during FilterChain execution
java.lang.OutOfMemoryError: Java heap space ]]