Avoid DatasetCreate exception with only one coordinate #8239
With only westLongitude added and the other three coordinates left
empty, we were getting the following exception. A null check was added
to prevent this.

Command [DatasetCreate dataset:132] failed: Exception thrown from bean:
javax.ejb.EJBTransactionRolledbackException: Exception thrown from
bean:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:
Error from server at http://localhost:8983/solr/collection1: ERROR:
[doc=dataset_132_draft] Error adding field
'solr_bboxtype'='ENVELOPE(null,null,null,null)' msg=Unable to parse
shape given formats "lat,lon", "x y" or as WKT because
java.text.ParseException: Expected a number input:
ENVELOPE(null,null,null,null)